language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base libgl1-mesa-dev curl
  - source /opt/qt*/bin/qt*-env.sh

script:
  - cd src/gui
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - cd ../..
  - mkdir -p astree/usr/share/applications # "make install" should do this
  - cp astree.desktop astree/usr/share/applications/astree.desktop # "make install" should do this
  - mkdir -p astre/usr/share/samples
  - mkdir -p astre/usr/share/samples/afocal
  - mkdir -p astre/usr/share/samples/eyepieces
  - mkdir -p astre/usr/share/samples/others
  - mkdir -p astre/usr/share/samples/refractors
  - mkdir -p astre/usr/share/samples/telescopes
  - cp -r samples/afocal/* astre/usr/share/samples/afocal
  - cp -r samples/eyepieces/* astre/usr/share/samples/eyepieces
  - cp -r samples/others/* astre/usr/share/samples/others
  - cp -r samples/refractors/* astre/usr/share/samples/refractors
  - cp -r samples/telescopes/* astre/usr/share/samples/telescopes
  - mkdir -p astree/usr/glass
  - cp -r glass/* astree/usr/glass
  - mkdir -p astree/usr/share/metainfo ; cp astree.appdata.xml astree/usr/share/metainfo/ # "make install" should do this
  - mkdir -p astree/usr/bin ; cp Astree astree/usr/bin/astree # "make install" should do this
  - mkdir -p astree/usr/share/icons/hicolor/scalable/apps ; touch astree/usr/share/icons/hicolor/scalable/apps/astree.svg  # "make install" should do this
  - find astree/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage astree/usr/share/applications/astree.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Astree*.AppImage*
  - # $GITHUB_TOKEN missing, please set it in the Travis CI settings of this project
  - # You can get one from https://github.com/settings/tokens
  - # As for now just upload artifacts on Transfer.sh and post link to Travis CI log
  - curl --upload-file Astree*.AppImage https://transfer.sh/Astree-nightly-x86_64.AppImage
  - echo ""

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
